apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: syfosmvarsel
  namespace: teamsykmelding
  labels:
    team: teamsykmelding
spec:
  image: {{ image }}
  replicas:
    min: 1
    max: 4
    cpuThresholdPercentage: 90
  port: 8080
  liveness:
    path: /is_alive
    initialDelay: 10
    timeout: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /is_ready
    initialDelay: 30
    periodSeconds: 5
    timeout: 1
  prometheus:
    enabled: true
    path: /prometheus
  resources:
    limits:
      cpu: 500m
      memory: 1Gi
    requests:
      cpu: 300m
      memory: 512Mi
  kafka:
    pool: nav-prod
  azure:
    application:
      enabled: true
      tenant: nav.no
  webproxy: true
  vault:
    enabled: true
    paths:
      - kvPath: serviceuser/data/prod/srvsyfosmvarsel
        mountPath: /secrets/serviceuser
      - kvPath: /kv/prod/fss/syfosmvarsel/teamsykmelding
        mountPath: /var/run/secrets/nais.io/vault
  ingresses:
    - "https://syfosmvarsel.nais.adeo.no"
  env:
    - name: DITT_SYKEFRAVAER_URL
      value: https://www.nav.no
    - name: MOUNT_PATH_VAULT
      value: /postgresql/prod-fss
    - name: PDL_GRAPHQL_PATH
      value: https://pdl-api.nais.adeo.no/graphql
    - name: PDL_SCOPE
      value: api://prod-fss.pdl.pdl-api/.default