apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: syfosmvarsel
  namespace: default
  labels:
    team: teamsykefravr
spec:
  image: {{ image }}
  replicas:
    min: 1
    max: 2
    cpuThresholdPercentage: 90
  port: 8080
  liveness:
    path: /is_alive
    initialDelay: 10
    timeout: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /is_ready
    initialDelay: 30
    periodSeconds: 5
    timeout: 5
  prometheus:
    enabled: true
    path: /prometheus
  resources:
    limits:
      cpu: 500m
      memory: 1Gi
    requests:
      cpu: 100m
      memory: 128Mi
  vault:
    enabled: true
  ingresses:
    - "https://syfosmvarsel.nais.preprod.local"
  env:
    - name: KAFKA_BOOTSTRAP_SERVERS_URL
      value: SSL://b27apvl00045.preprod.local:8443,SSL://b27apvl00046.preprod.local:8443,SSL://b27apvl00047.preprod.local:8443
    - name: TJENESTER_URL
      value: https://tjenester-q1.nav.no
    - name: SECURITY_TOKEN_SERVICE_URL
      value: https://sts-q1.preprod.local/SecurityTokenServiceProvider/
    - name: DISKRESJONSKODE_ENDPOINT_URL
      value: https://wasapp-q1.adeo.no/tpsws/Diskresjonskode
    - name: MOUNT_PATH_VAULT
      value: /postgresql/preprod-fss
    - name: MQ_HOST_NAME
      value: b27apvl176.preprod.local
    - name: MQ_PORT
      value: '1413'
    - name: MQ_GATEWAY_NAME
      value: MQ1LSC02
    - name: MQ_CHANNEL_NAME
      value: Q1_SYFOSMVARSEL
    - name: BESTVARSELMHANDLING_QUEUENAME
      value: QA.Q1_VARSELPRODUKSJON.BEST_VARSEL_M_HANDLING
    - name: PDL_GRAPHQL_PATH
      value: https://pdl-api.nais.preprod.local/graphql