apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: syfosmvarsel
  namespace: teamsykmelding
  labels:
    team: teamsykmelding
spec:
  image: {{ image }}
  replicas:
    min: 1
    max: 2
    cpuThresholdPercentage: 90
  port: 8080
  liveness:
    path: /is_alive
    initialDelay: 10
    timeout: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /is_ready
    initialDelay: 30
    periodSeconds: 5
    timeout: 1
  prometheus:
    enabled: true
    path: /prometheus
  resources:
    limits:
      cpu: 500m
      memory: 1Gi
    requests:
      cpu: 100m
      memory: 128Mi
  azure:
    application:
      enabled: true
      tenant: trygdeetaten.no
  vault:
    enabled: true
    paths:
      - kvPath: serviceuser/data/dev/srvsyfosmvarsel
        mountPath: /secrets/serviceuser
      - kvPath: /kv/preprod/fss/syfosmvarsel/teamsykmelding
        mountPath: /var/run/secrets/nais.io/vault
  ingresses:
    - "https://syfosmvarsel.nais.preprod.local"
  env:
    - name: KAFKA_BOOTSTRAP_SERVERS_URL
      value: SSL://b27apvl00045.preprod.local:8443,SSL://b27apvl00046.preprod.local:8443,SSL://b27apvl00047.preprod.local:8443
    - name: TJENESTER_URL
      value: https://tjenester-q1.nav.no
    - name: MOUNT_PATH_VAULT
      value: /postgresql/preprod-fss
    - name: PDL_GRAPHQL_PATH
      value: https://pdl-api.nais.preprod.local/graphql