apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: syfosmvarsel
  namespace: teamsykmelding
  labels:
    team: teamsykmelding
spec:
  gcp:
    sqlInstances:
      - name: smvarsel-instance
        type: POSTGRES_14
        diskSize: 10
        databases:
          - name: smvarsel
            envVarPrefix: NAIS_DATABASE
        diskAutoresize: true
        highAvailability: false
        diskType: SSD
        insights:
          enabled: true
  image: {{ image }}
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 90
  port: 8080
  liveness:
    path: /internal/is_alive
    initialDelay: 10
    timeout: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /internal/is_ready
    initialDelay: 30
    periodSeconds: 5
    timeout: 1
  prometheus:
    enabled: true
    path: /internal/prometheus
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
    logging:
      destinations:
        - id: loki
        - id: elastic
  resources:
    limits:
      memory: 1Gi
    requests:
      cpu: 100m
      memory: 512Mi
  kafka:
    pool: nav-dev
  env:
    - name: DITT_SYKEFRAVAER_URL
      value: https://www.ekstern.dev.nav.no
