apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: syfosmvarsel
  namespace: teamsykmelding
  labels:
    team: teamsykmelding
spec:
  gcp:
    sqlInstances:
      - name: smvarsel-instance
        type: POSTGRES_14
        diskSize: 10
        databases:
          - name: smvarsel
            envVarPrefix: NAIS_DATABASE
        diskAutoresize: true
        highAvailability: false
        diskType: SSD
        insights:
          enabled: true
  image: {{ image }}
  replicas:
    min: 1
    max: 2
    cpuThresholdPercentage: 90
    disableAutoScaling: true
  port: 8080
  liveness:
    path: /internal/is_alive
    initialDelay: 10
    timeout: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /internal/is_ready
    initialDelay: 30
    periodSeconds: 5
    timeout: 1
  prometheus:
    enabled: true
    path: /internal/prometheus
  resources:
    limits:
      cpu: 500m
      memory: 1Gi
    requests:
      cpu: 100m
      memory: 128Mi
  kafka:
    pool: nav-dev
  azure:
    application:
      enabled: true
      tenant: trygdeetaten.no
  webproxy: false
  vault:
    enabled: false
  env:
    - name: DITT_SYKEFRAVAER_URL
      value: https://www-gcp.dev.nav.no
    - name: PDL_GRAPHQL_PATH
      value: https://pdl-api.dev-fss-pub.nais.io/graphql
    - name: PDL_SCOPE
      value: api://dev-fss.pdl.pdl-api/.default